# Generated by Django 3.2.2 on 2024-02-08 11:16

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="term",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1")),
                    django.core.validators.MaxValueValidator(Decimal("12")),
                ],
                verbose_name="Срок (месяцы)",
            ),
        ),
    ]
