# Generated by Django 3.2.2 on 2024-02-12 14:45

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targets", "0002_alter_target_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="start_amount",
            field=models.DecimalField(
                decimal_places=2,
                default="0",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Начальная сумма",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="term",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                verbose_name="Срок (месяцы)",
            ),
        ),
        migrations.CreateModel(
            name="TargetChangeBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата изменения баланса")),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes_balance",
                        to="targets.target",
                        verbose_name="Цель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменние баланса цели",
                "verbose_name_plural": "Изменния баланса цели",
            },
        ),
    ]
