# Generated by Django 3.2.2 on 2024-02-14 09:26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targets", "0003_auto_20240212_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата завершения цели"
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата создания цели"
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="start_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Начальная сумма",
            ),
        ),
        migrations.AlterField(
            model_name="targetchangebalance",
            name="date",
            field=models.DateField(blank=True, verbose_name="Дата изменения баланса"),
        ),
    ]
