# Generated by Django 3.2.2 on 2024-02-19 11:15

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targets", "0005_auto_20240214_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="end_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Сколько хотите накопить",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="increase_percent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Процент",
            ),
        ),
        migrations.AlterField(
            model_name="targetchangebalance",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма"
            ),
        ),
    ]
