# Generated by Django 3.2.2 on 2023-11-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pockets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "Операция", "verbose_name_plural": "Операции"},
        ),
        migrations.RemoveField(
            model_name="transactioncategory",
            name="category_type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Доход"), ("expense", "Расход")],
                default="expense",
                max_length=7,
                verbose_name="Тип категории",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="pockets.transactioncategory",
                verbose_name="Категория",
            ),
        ),
    ]
